INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('favehotel Graha Agung Surabaya','Sebuah Hotel Mewah di Surabaya Persembahan dari Archipelago International Group','Jawa Timur','Surabaya','Jl. Mayjen Yono Soewoyo Pakuwon Indah Square AKII No.10-11, Surabaya',442860.0),
	 ('The Sun Hotel Sidoarjo','Hotel Bintang 3 Pertama dan Satu-satunya di Sidoarjo','Jawa Timur','Surabaya','Jl. Pahlawan No.1,Sidokumpul, Sidoarjo, Surabaya, Jawa Timur, Indonesia',305000.0),
	 ('Grand Surabaya Hotel','Penginapan Yang Tenang Dan Nyaman Di Surabaya.','Jawa Timur','Surabaya','Jl. Pemuda 19-21, Surabaya, Indonesia',324999.3333),
	 ('The WIN Hotel Surabaya','WIN Hotel adalah hotel smart bintang 3 yang menawarkan layanan tulus, cocok untuk semua wisatawan','Jawa Timur','Surabaya','Jl. Embong Tanjung 46 - 48 Surabaya, Jawa Timur, Indonesia',310947.25),
	 ('POP! Hotel Stasiun Kota Surabaya','Sebuah Hotel Modern yang Terjangkau di Jawa Timur','Jawa Timur','Surabaya','Jl. Waspada No.58, Surabaya, Jawa Timur, Indonesia',276333.3333),
	 ('Evora Hotel Surabaya','Ketika bisnis dan kenyamanan sinergi di satu tempat persembahan Evora Hotel Surabaya','Jawa Timur','Surabaya','Jl. Menur 18 - 20, Surabaya, Indonesia',283000.0),
	 ('MaxOneHotels at Dharmahusada','Pengalaman kenyamanan maksimum dalam kesederhanaan MaxOne Hotel.','Jawa Timur','Surabaya','Jl. Dharmahusada No. 189, Gubeng, Surabaya, Jawa Timur, Indonesia',463328.5),
	 ('Zoom Dharmahusada Hotel','Akomodasi modern, nyaman, dan tenang di Surabaya','Jawa Timur','Surabaya','Jl. Raya Dharmahusada No. 188, Surabaya, Indonesia',309540.0),
	 ('Neo+ Waru Sidoarjo by ASTON','Pilihan akomodasi yang ideal untuk Pasangan, Backpacker dan Liburan Keluarga.','Jawa Timur','Surabaya','Jl. S. Parman No. 52-54, Waru, Sidoarjo, Surabaya, Jawa Timur, Indonesia',293122.5),
	 ('favehotel Sidoarjo','Penginapan Yang Tenang Dan Nyaman di Sidoarjo.','Jawa Timur','Surabaya','Jl. Jenggolo No. 15, Pucang, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur, Indonesia',447216.0);
INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('News Front One Hotel Surabaya','Rasakan keramahan kota Surabaya di News Hotel Surabaya','Jawa Timur','Surabaya','Jl. Pondok Maspion Blok S No. 1, Pepelegi, Waru,  Sidoarjo, Jawa Timur, Surabaya, Indonesia',239118.3333),
	 ('Gunawangsa Manyar Hotel','Sebuah Hotel bintang 3 yang Mudah, Simpel, dan Menyegarkan di Surabaya','Jawa Timur','Surabaya','Menur Pumpungan No 62 Manyar, Surabaya',449619.3333),
	 ('Zest Hotel Jemursari Surabaya','Persembahan kembali dari Swiss-BelHotel Grup hotel premium di Surabaya','Jawa Timur','Surabaya','Jl. Raya Prapen 266, Surabaya',272649.0),
	 ('The Life Hotel Surabaya','Akomodasi yang Ideal untuk Pebisnis, Wisatawan dan Keluarga di Surabaya','Jawa Timur','Surabaya','Jl. Kusuma Bangsa No.41, Surabaya, Indonesia',151496.0),
	 ('Best Western Papilio Hotel','Welcome to Best Western Papilio Hotel!','Jawa Timur','Surabaya','Jl. Ahmad Yani 176 - 178, Surabaya',305890.0),
	 ('G Suites Hotel by AMITHYA','Hotel Entertainment dengan penuh keceriaan di Surabaya.','Jawa Timur','Surabaya','Jl. Raya Gubeng No.54, Surabaya, Jawa Timur, Indonesia',591916.6667),
	 ('Hotel Gunawangsa MERR','Akomodasi yang Ideal untuk Pebisnis, Wisatawan dan Keluarga di Surabaya','Jawa Timur','Surabaya','Jl. Kedung Baruk No. 96, Surabaya, Jawa Timur, Indonesia',407933.6),
	 ('Sumi Hotel Surabaya','Penginapan tenang dan nyaman di Sumi Hotel','Jawa Timur','Surabaya','Jl. Mayjend Sungkono No. 37 A, Surabaya, Indonesia',291772.0),
	 ('Red Planet Surabaya','Hotel yang Strategis dan Terjangkau oleh Red Planet Surabaya','Jawa Timur','Surabaya','Jl. Arjuna No.64-66, Surabaya, Indonesia',336493.6667),
	 ('Great Diponegoro Hotel Surabaya','Hotel yang cocok Untuk Wisatawan Bisnis, Keluarga dan berlibur, dengan makanan yang Lezat','Jawa Timur','Surabaya','Jl. Diponegoro No.215, Darmo, Surabaya',251627.0);
INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('Quest Hotel Darmo - Surabaya by ASTON','Sebuah Hotel yang Nyaman, Lengkap, dan Terjangkau di Surabaya','Jawa Timur','Surabaya','Jl. Ronggolawe No. 27-29, Surabaya, Jawa Timur, Indonesia',360217.0),
	 ('Zoom Hotel Jemursari','Sebuah Hotel yang Nyaman, Lengkap, dan Terjangkau di Surabaya','Jawa Timur','Surabaya','Jemursari Raya 109 B-C Surabaya, Jemursari, Surabaya',330639.3333),
	 ('Hotel 88 Embong Kenongo ( Kayoon )','Akomodasi yang nyaman untuk bisnis dan liburan di Surabaya','Jawa Timur','Surabaya','Jl. Kenongo No.17, Embong Kaliasin, Genteng, Surabaya, Jawa Timur, Indonesia',280000.0),
	 ('Continent My Tower Hotel, Surabaya - Rungkut','Penginapan Yang Tenang Dan Nyaman di Surabaya.','Jawa Timur','Surabaya','Jl. Rungkut Industri Raya No. 4, Surabaya, Jawa Timur, Indonesia',298303.4),
	 ('Bonnet Hotel Surabaya','Persembahan hotel Bintang 3 dari Kore Hotel Internasional di Surabaya','Jawa Timur','Surabaya','Jl. Manyar Kertoarjo V No.62, Mojo',220675.0),
	 ('Premier Place Surabaya Airport','Sebuah Hotel yang Nyaman, Lengkap, dan Terjangkau di Surabaya','Jawa Timur','Surabaya','Jl. Raya Bandara Juanda No.73, Semawalang, Semambung, Kec. Gedangan, Kabupaten Sidoarjo, Jawa Timur',378248.3333),
	 ('Wyndham Surabaya','Penginapan Yang Tenang Dan Nyaman di Surabaya.','Jawa Timur','Surabaya','Jl. Basuki Rahmat 67-73, Genteng, Surabaya, Jawa Timur, Indonesia',567187.5),
	 ('Front One Inn Sidoarjo','Penginapan Yang Tenang Dan Nyaman di Sidoarjo.','Jawa Timur','Surabaya','Jl. Trunojoyo No. 41, Sidoarjo, Jawa Timur, Indonesia',250000.0),
	 ('Hotel 88 Embong Malang','Memberikan Harga yang  Murah dan Suasana Nyaman','Jawa Timur','Surabaya','Jl. Embong Malang No.84, Surabaya',231033.3333),
	 ('Yello Hotel Jemursari','Sebuah hotel yang nyaman dan strategis di Surabaya persembahan Group Tauzia Hotel Management','Jawa Timur','Surabaya','Jl. Raya Jemursari 176, Surabaya, Jawa Timur, Indonesia',513000.0);
INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('Luminor Hotel Airport Sidoarjo','Hotel yang nyaman dan modern di Sidoarjo.','Jawa Timur','Surabaya','Jl. Pahlawan, Jetis, Lemahputro, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur, Indonesia',390244.0),
	 ('BATIQA Hotel Darmo - Surabaya','Rasakan keramah tamahan asli Indonesia di Surabaya.','Jawa Timur','Surabaya','Jl. Darmokali No. 60, Surabaya, Indonesia',348600.0),
	 ('Holiday Inn Express Surabaya CenterPoint','Sebuah penginapan yang nyaman. Terletak di daerah Surabaya, Jawa Timur.','Jawa Timur','Surabaya','Jl. Kedungdoro No.58, Surabaya',478747.3333),
	 ('Hotel Ciputra World Surabaya','Sebuah Hotel Mewah dan Elit di Surabaya','Jawa Timur','Surabaya','Jl. Mayor Jend Sungkono 87-89 Gunung Sari, Dukuh Pakis, Surabaya',847166.6667),
	 ('Deka Hotel','Penginapan Yang Tenang Dan Nyaman di Surabaya.','Jawa Timur','Surabaya','Jl. Mayjen HR. Muhammad No. 24, Putat Gede, Sukomanunggal, Surabaya, Jawa Timur, Indonesia',355011.6),
	 ('Swiss-Belinn Tunjungan Surabaya','Akomodasi bintang 3, yang nyaman dan tenang di Surabaya','Jawa Timur','Surabaya','Jl. Tunjungan No.101, Surabaya, Indonesia',748333.3333),
	 ('DeMira Hotel','Penginapan tenang dan nyaman di deMIRA Hotel','Jawa Timur','Surabaya','Jl. Sumatra 92 A, Surabaya, Jawa Timur, Indonesia',250000.0),
	 ('Hotel 88 Kedungsari ( Kedungdoro )','Penginapan Yang Tenang Dan Nyaman di Tegalsari.','Jawa Timur','Surabaya','Jl. Kedungsari No. 76 - 78, Tegalsari, Surabaya, Indonesia',236833.3333),
	 ('MaxOneHotels at Tidar Surabaya','Pengalaman kenyamanan maksimum dalam kesederhanaan MaxOne Hotel','Jawa Timur','Surabaya','Jl. Tidar No. 5, Surabaya, Indonesia',400231.1667),
	 ('POP! Hotel Gubeng','Sebuah Hotel Modern yang Terjangkau di Gubeng, Jawa Timur','Jawa Timur','Surabaya','Jl. Bangka 8-18, Gubeng, Surabaya',313000.0);
INSERT INTO db_hotel.hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('UNO Smartstay Hotel Surabaya','Sebuah pilihan cerdas saat anda memilih UNO Smartstay Hotel Surabaya','Jawa Timur','Surabaya','Jl. Genteng Besar No. 80, Genteng, Surabaya, Jawa Timur, Indonesia',168800.0),
	 ('Grace Setia Hotel','BARU. Ekonomis, bersih, nyaman.','Jawa Timur','Surabaya','Jl. MERR kalijudan k 158, Kalijudan, Surabaya, Indonesia',334125.0),
	 ('Swiss-Belinn Airport Surabaya','Penginapan Yang Cocok Untuk Bisnis Dan Bersantai','Jawa Timur','Surabaya','Jl. Raya Juanda KM 1,88, Gedangan, Sidoarjo, Surabaya, Indonesia',442666.6667),
	 ('Midtown Hotel Surabaya','Sebuah Hotel Bintang 3 yang Nyaman  dan Terjangkau di Surabaya','Jawa Timur','Surabaya','Jl. Basuki Rahmat No.76, Surabaya Center',455040.3333),
	 ('Amaris Hotel Embong Malang','Bagaikan tinggal di rumah persembahan Amaris Hotel Embong Malang, Surabaya.','Jawa Timur','Surabaya','Jl. Kedung Doro No 1-3, Surabaya Center, Surabaya, Indonesia',382000.0),
	 ('Oval Hotel Surabaya','Kebanggaan Surabaya - Hotel Bentuk Oval Pertama di Asia','Jawa Timur','Surabaya','Jl. Diponegoro No.23, Surabaya',291666.6667),
	 ('Vasa Hotel Surabaya','Pilihan akomodasi ideal untuk Wisatawan Bisnis, dan Liburan Keluarga.  ','Jawa Timur','Surabaya','Jl. HR. Muhammad No.31, Sukomanunggal, Surabaya, Jawa Timur, Indonesia',1597200.0),
	 ('Hotel Sulawesi Kertajaya','Pilihan akomodasi ideal untuk Wisatawan Bisnis, Backpacker, dan Liburan Keluarga.','Jawa Timur','Surabaya','Jalan Kertajaya IV Raya No 2 BLK, Gubeng, Surabaya, Jawa Timur, Indonesia',205883.0),
	 ('Narita Classic Hotel Surabaya','Sebuah Hotel yang Nyaman, Lengkap, dan Terjangkau di Surabaya','Jawa Timur','Surabaya','Jl. Barata Jaya Street XVII / 57-59, Surabaya',450000.0),
	 ('Citihub Hotel @ Pecindilan Surabaya','Sebuah Hotel Nyaman yang Terjangkau di Surabaya Persembahan Citihub Group Indonesia','Jawa Timur','Surabaya','Jl. Raya Pecindilan No. 66, Surabaya, Indonesia',260000.0);
INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('Casa Sidoluhur 17','Pilihan akomodasi yang ideal untuk Pasangan, Backpacker dan Liburan Keluarga.','Jawa Timur','Surabaya','Jl. Sidoluhur No. 17, RT 010 RW 02, Surabaya, Jawa Timur, Indonesia',168931.75),
	 ('Chiaro Hotel','Penginapan yang nyaman di tengah kota Sidoarjo.','Jawa Timur','Surabaya','Jl. Trunojoyo No. 17, Kota Sidoarjo, Sidoarjo, Jawa Timur, Indonesia',354750.0),
	 ('Hotel Tanjung','Pilihan akomodasi yang ideal untuk Pasangan, Backpacker dan Liburan Keluarga.','Jawa Timur','Surabaya','Jl.Panglima Sudirman No.43-45, Genteng, Surabaya, Indonesia',209893.0),
	 ('Hotel Kenongo','Akomodasi modern, nyaman, dan tenang di Surabaya.','Jawa Timur','Surabaya','Jl. Embong Kenongo No.12, Surabaya, Indonesia',231806.3333),
	 ('Hersya Front One Inn','Penginapan tenang dan nyaman di Surabaya','Jawa Timur','Surabaya','Jl. Ketintang Baru III No. 58, Surabaya 60231, Indonesia',221000.0),
	 ('Graha DPT 33','Akomodasi yang strategis dan terjangkau di jantung kota Surabaya','Jawa Timur','Surabaya','Jl. Darmo Permai Timur No. 3 Surabaya',288733.3333),
	 ('Cleo Hotel Walikota','Pilihan hotel yang tepat bila berkunjung ke Surabaya','Jawa Timur','Surabaya','Jl Walikota Mustajab No 59, Surabaya, Indonesia',609375.0),
	 ('Cleo Hotel Basuki Rahmat','Hotel bintang 2 untuk perjalanan bisnis ataupun liburan di Surabaya','Jawa Timur','Surabaya','Jl. Basuki Rahmat No. 11 Surabaya - Jawa Timur',414000.0),
	 ('Rock Hotel','Penginapan modern yang cocok untuk Anda berkunjung ke Surabaya bersama keluarga','Jawa Timur','Surabaya','Jl Barata Jaya 17 No 55, Surabaya, Jawa Timur, Indonesia',310000.0),
	 ('Namira Syariah Surabaya Hotel','Penginapan Yang Tenang Dan Nyaman di Surabaya','Jawa Timur','Surabaya','Wisma Pagesangan Street No. 203, Jambangan, Surabaya 60233, Indonesia',399999.0);
INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('Walan Syariah Hotel Surabaya','Sebuah penginapan yang strategis, nyaman dan terjangkau di Surabaya','Jawa Timur','Surabaya','Jl. Raya Sedati Agung 1 Betro Juanda, Surabaya',350000.0),
	 ('Verwood Hotel and Serviced Residence','Penginapan Yang Tenang Dan Nyaman di Verwood Hotel and Serviced Residence','Jawa Timur','Surabaya','Jl. Raya Kupang Indah, Dukuh Pakis, Surabaya 60189, Indonesia',661344.8333),
	 ('Grand Kalimas Syariah','Sebuah Penginapan yang Nyaman dan Terjangkau di Surabaya.','Jawa Timur','Surabaya','Jl. KH. Mas Mansyur 151, Surabaya, Indonesia',368033.3333),
	 ('Andalus Hotel','Akomodasi yang luar biasa di Surabaya.','Jawa Timur','Surabaya','Jl. Sultan Iskandar Muda No. 65, Ampel, Surabaya, Indonesia',160000.0),
	 ('Hotel Ashofa Surabaya','Hotel yang nyaman, bersih dan aman. Berlokasi strategis.','Jawa Timur','Surabaya','Jl. By Pass Juanda Baru, Sedati, Surabaya',212500.0),
	 ('Maumu Hotel and Lounge','Hotel yang Nyaman dan Modern di Jantung Kota Surabaya','Jawa Timur','Surabaya','Jl. Walikota Mustajab 29-31, Surabaya, Jawa Timur, Indonesia',240000.0),
	 ('Grand Puri','Akomodasi yang nyaman dan modern di Surabaya','Jawa Timur','Surabaya','Jl. Kupang Indah IX No.1 , Dukuh Pakis, Surabaya',1050400.0),
	 ('GreenHaus Inn','Akomodasi yang nyaman dan modern di Surabaya','Jawa Timur','Surabaya','Jl. Dinoyo No.86 RT.008/RW.03, Keputran Kec. Tegalsari Kota SBY Jawa Timur',220720.5),
	 ('Hotel Shabine','Penginapan yang nyaman dan tenang','Jawa Timur','Surabaya','Jl. Rungkut Asri Utara No.58, Rungkut, Surabaya, Jawa Timur, Indonesia',157692.0),
	 ('Hotel Omah Ampel','Akomodasi yang nyaman dan modern di Surabaya','Jawa Timur','Surabaya','Jl. Nyamplungan No. 77 - 79',120902.3333);
INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('Grand Darmo Suite by AMITHYA','Sebuah Hotel mewah yang baru di Surabaya','Jawa Timur','Surabaya','Jl. Progo No.1-3, Surabaya, Jawa Timur, Indonesia',671099.0),
	 ('I&M Hotel','Hotel yang Strategis dan Terjangkau oleh I&M Hotel.','Jawa Timur','Surabaya','Jl. Argopuro No.49-51, Surabaya, Indonesia',250486.2),
	 ('POP! Hotel Diponegoro Surabaya','Sebuah Hotel Modern yang Terjangkau di Jawa Timur','Jawa Timur','Surabaya','Jl. Diponegoro No 33 Darmo, Surabaya, Indonesia',258000.0),
	 ('Citra Suites Raya Bratang Binangun','Penginapan yang nyaman dan tenang di Surabaya','Jawa Timur','Surabaya','Jl. Bratang Binangun 53A (Seberang Bank Bukopin RMI Ngagel), Surabaya, Indonesia',140000.0),
	 ('Swiss-Belinn Manyar Surabaya','Sebuah Hotel Bintang 3 Internasional persembahan Grup Swiss-Belhotel di Surabaya','Jawa Timur','Surabaya','Jl.Manyar Kertoarjo No.100, Surabaya Jawa Timur',406000.0),
	 ('Hotel Sahid Surabaya','Tempat Spesial Dimana Bisnis Anda Akan Ditangani Dengan Keramahan.','Jawa Timur','Surabaya','Jl. Sumatera No.1-5, Surabaya Pusat, Surabaya',392500.0),
	 ('Hotel Sulawesi Gorontalo - Surabaya','Penginapan yang modern dan nyaman di Surabaya.','Jawa Timur','Surabaya','Jl. Embong Cerme No 5, Genteng, Surabaya, Jawa Timur, Indonesia',235295.0),
	 ('Brava Suites by Zia Surabaya','Penginapan Yang Cocok Untuk Bisnis Dan Bersantai','Jawa Timur','Surabaya','Jl. Mayjend Sungkono No. 212-214, Putat Gede, Suko Manunggal, Surabaya, Indonesia',468750.0),
	 ('Citihub Hotel @Tunjungan Surabaya','Sebuah Hotel Nyaman yang Terjangkau di Surabaya Persembahan Citihub Group Indonesia','Jawa Timur','Surabaya','Jl.Gubernur Suryo 1-J (D/H Jalan Pemuda) Surabaya, Jawa Timur, Indonesia',255000.0),
	 ('Varna Culture Hotel Surabaya','Sebuah hotel bintang-3 mewah di Surabaya','Jawa Timur','Surabaya','Jl Tunjungan No 51 Surabaya',412500.0);
INSERT INTO hotel (hotel_name,hotel_desc,province,city,address,price_per_night) VALUES
	 ('Sentosa Homestay','Penginapan Yang Tenang Dan Nyaman di Dukuh Pakis, Surabaya.','Jawa Timur','Surabaya','Jln. Kencana Sari Barat B no.16',300000.0),
	 ('Tilamas Hotel','Sebuah Hotel yang Lengkap dan Strategis oleh Grup Tilamas di Surabaya','Jawa Timur','Surabaya','Jl. Raya Juanda No.88, Juanda, Surabaya, Jawa Timur, Indonesia',344738.0),
	 ('Graha Cempaka Boutique Hotel','Kenyamanan untuk berbisnis dan berekreasi di hotel bintang 3 di pusat kota Surabaya','Jawa Timur','Surabaya','Jl. Tenggilis Mejoyo G-7, Surabaya, Jawa Timur, Indonesia',400000.0),
	 ('Choice City Hotel Surabaya','Pilihan akomodasi yang ideal bagi keluarga, pebisnis dan wisatawan di pusat kota Surabaya','Jawa Timur','Surabaya','BG Junction Mall Lantai P - 9, Jl. Bubutan I No.7, Surabaya, Indonesia',336666.6667),
	 ('Horison Arcadia Surabaya','Akomodasi yang luar biasa di Surabaya.','Jawa Timur','Surabaya','Jl. Rajawali No. 9-11, Surabaya, Indonesia',512736.6667),
	 ('Hotel Permata','Akomodasi yang nyaman dan modern di Sidoarjo','Jawa Timur','Surabaya','Jl. Raya Pabean No. 38 Sedati, SIdoarjo, Jawa Timur, Indonesia',195686.5),
	 ('A1 Hotel','A1 Hotel  is located in the heart of the business area of Surabaya','Jawa Timur','Surabaya','Gallery bukit indah RK 3 No. 20-21 ,Lontar, Sambikerep, Surabaya, Jawa Timur, Indonesia',160458.5),
	 ('Semampir Residence','Semampir Residence is located in the heart of the business area of Surabaya','Jawa Timur','Surabaya','Jl. Semampir Tengah 38, Medokan Semampir, Sukolilo, Surabaya, Jawa Timur, Indonesia',171848.0);